<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>StreamCart.Infra</RootNamespace>
    <!-- CDK's generated APIs trip a few analyzers; they are not useful for IaC code. -->
    <NoWarn>$(NoWarn);CS0618;CA1806</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.CDK.Lib" />
    <PackageReference Include="Constructs" />
  </ItemGroup>

</Project>
